server:
  port: 9103

grpc:
  server:
    port: 9003

spring:
  application:
    name: dispatch-coordinator-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dispatch_coordinator_service_db
    username: uber
    password: uber_password
