server:
  port: 9130

grpc:
  server:
    port: 9030

spring:
  application:
    name: auth-security-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_security_service_db
    username: uber
    password: uber_password
