server:
  port: 9101

grpc:
  server:
    port: 9001

spring:
  application:
    name: supply-locator-service
  datasource:
    url: jdbc:postgresql://localhost:5432/supply_locator_service_db
    username: uber
    password: uber_password
