server:
  port: 9128

grpc:
  server:
    port: 9028

spring:
  application:
    name: driver-earnings-analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_earnings_analytics_service_db
    username: uber
    password: uber_password
