server:
  port: 9125

grpc:
  server:
    port: 9025

spring:
  application:
    name: driver-compliance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_compliance_service_db
    username: uber
    password: uber_password
