server:
  port: 9129

grpc:
  server:
    port: 9029

spring:
  application:
    name: rider-profile-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rider_profile_service_db
    username: uber
    password: uber_password
