server:
  port: 9110

grpc:
  server:
    port: 9010

spring:
  application:
    name: trip-reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trip_reservation_service_db
    username: uber
    password: uber_password
