server:
  port: 9123

grpc:
  server:
    port: 9023

spring:
  application:
    name: driver-onboarding-service
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_onboarding_service_db
    username: uber
    password: uber_password
