server:
  port: 9136

grpc:
  server:
    port: 9036

spring:
  application:
    name: event-streaming-hub-service
  datasource:
    url: jdbc:postgresql://localhost:5432/event_streaming_hub_service_db
    username: uber
    password: uber_password
