server:
  port: 8085

grpc:
  server:
    port: 9085

spring:
  application:
    name: rider-domain-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/rider_domain_gateway_db
    username: uber
    password: uber_password
